version: '3'
services:
  rtsp2icecast:
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      RTSP_URL: rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream
      FFMPEG_LOG_LEVEL: warning
      ICECAST_URL: 127.0.0.1
      ICECAST_PASSWORD: yourPassword
      ICECASE_MOUNTPOINT: yourMountPoint
